// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"BootOpeningDemo","status":true,"description":"タイトル画面を出す前にオープニングデモから開始します","parameters":{"firstMapId":"2","startX":"0","startY":"0"}},
{"name":"SSPlayerForRPGMV","status":true,"description":"SpriteStudioで作成されたアニメーションを再生できるようにするプラグインです。","parameters":{"アニメーションフォルダ":"img/animations/ssas","色調変更範囲を制限する":"OFF","色調変更をフィルタで行う":"OFF"}},
{"name":"ChangeCharacterToSS","status":true,"description":"アクターやイベントのアニメーショングラフィックをSpriteStudioのアニメーションに置きかえるプラグインです。","parameters":{"アニメ名(移動)":"walk","アニメ名(停止)":"idle","ダッシュ時にアニメーションを変更する":"ON","アニメ名(ダッシュ)":"dash"}}
];
