// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SSPlayerForRPGMV","status":true,"description":"SpriteStudioで作成されたアニメーションを再生できるようにするプラグインです。","parameters":{"Animation File Path":"img/animations/ssas"}},
{"name":"ChangeCharacterToSS","status":true,"description":"","parameters":{}}
];
